fn main() {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out = std::path::PathBuf::from(&crate_dir).join("../../sdk/c/overlayward.h");
    if let Ok(bindings) = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_no_includes()
        .with_sys_include("stdint.h")
        .with_sys_include("stdbool.h")
        .with_sys_include("stddef.h")
        .with_include_guard("OVERLAYWARD_H")
        .with_autogen_warning("/* Auto-generated by cbindgen. Do not edit. */")
        .generate()
    {
        bindings.write_to_file(&out);
    }
}
