#ifndef OVERLAYWARD_H
#define OVERLAYWARD_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct OwClient {
  uint8_t _opaque[0];
} OwClient;

typedef struct OwSandbox {
  char *sandbox_id;
  char *name;
  char *status;
} OwSandbox;

typedef struct OwStatus {
  bool ok;
  char *error_message;
} OwStatus;

struct OwClient *ow_client_new(const char *endpoint, const char *token);

void ow_client_free(struct OwClient *client);

struct OwSandbox *ow_sandbox_create(struct OwClient *client,
                                    const char *name,
                                    int32_t cpu,
                                    const char *memory);

struct OwStatus ow_sandbox_start(struct OwClient *client, const char *sandbox_id);

struct OwStatus ow_sandbox_stop(struct OwClient *client, const char *sandbox_id, bool force);

struct OwStatus ow_sandbox_destroy(struct OwClient *client, const char *sandbox_id);

void ow_sandbox_free(struct OwSandbox *sb);

void ow_status_free_message(char *msg);

#endif  /* OVERLAYWARD_H */
